# resources:
  # repositories:
  # - repository: e2etest # The name used to reference this repository in the checkout step
  #   type: github
  #   endpoint: jaysonmc
  #   name: jaysonmc/temp-ocio-powerplatform-bdd-tests
  #   ref: publish-reviews-sarif

trigger:
- main

jobs:
  - job: e2etests
    timeoutInMinutes: 120
    pool:
        vmImage: 'ubuntu-latest'
    container:
        image: mcr.microsoft.com/playwright:focal
        volumes: [e2e-reviews]

    steps:
        # - checkout: e2etest     
        - task: Npm@1
          inputs:
            command: 'install'
          displayName: 'installing dependencies'
# using CmdLine for the following instead of Npm because npm buffers the entire output
        - task: CmdLine@2  
          displayName: 'Running path e2e tests'
          continueOnError: true
          inputs:
            script: |
              mkdir junit
              HAIBUN_OUTPUT_DEST=junit/paths.xml HAIBUN_OUTPUT=~@haibun/out-xunit/build/out-xunit HAIBUN_TITLE="Path e2e tests" HAIBUN_DEST=e2e HAIBUN_O_OUTREVIEWS_TRACE_STORAGE=StorageFS HAIBUN_O_WEBPLAYWRIGHT_STORAGE=StorageFS HAIBUN_ENVC=${_ENVC} npm run test-public-happy

        - task: CmdLine@2 
          displayName: 'Running regression e2e tests'
          continueOnError: true        
          inputs:
            script: |
              HAIBUN_OUTPUT_DEST=junit/regressions.xml HAIBUN_OUTPUT=~@haibun/out-xunit/build/out-xunit HAIBUN_TITLE="Regression e2e tests" HAIBUN_DEST=regressions HAIBUN_O_OUTREVIEWS_TRACE_STORAGE=StorageFS HAIBUN_O_WEBPLAYWRIGHT_STORAGE=StorageFS HAIBUN_ENVC=${_ENVC} npm run test-public-regressions

        - task: CmdLine@2
          displayName: 'Generate sarif indexes'
          continueOnError: true
          inputs:
            script: |
              HAIBUN_DEST=sarif HAIBUN_O_AZURESTORAGEBLOB_DESTINATION='staticanalysis-sc' HAIBUN_O_SARIF_TRACE_STORAGE=AzureStorageBlob HAIBUN_O_SARIF_INDEX_STORAGE=StorageFS HAIBUN_O_AZURESTORAGEBLOB_ACCOUNT=${_O_AZURESTORAGEBLOB_ACCOUNT} HAIBUN_O_AZURESTORAGEBLOB_KEY=${_O_AZURESTORAGEBLOB_KEY}  npm run test-pipeline-index-sarif

        - task: CmdLine@2
          displayName: 'Generate test result indexes'
          continueOnError: true
          inputs:
            script: |
              HAIBUN_O_OUTREVIEWS_TRACE_STORAGE=StorageFS HAIBUN_O_OUTREVIEWS_PUBLISH_STORAGE=AzureStorageBlob HAIBUN_O_OUTREVIEWS_INDEX_STORAGE=StorageFS HAIBUN_O_OUTREVIEWS_REVIEWS_STORAGE=AzureStorageBlob HAIBUN_O_AZURESTORAGEBLOB_DESTINATION=e2e-reviews-sc HAIBUN_O_AZURESTORAGEBLOB_ACCOUNT=${_O_AZURESTORAGEBLOB_ACCOUNT} HAIBUN_O_AZURESTORAGEBLOB_KEY=${_O_AZURESTORAGEBLOB_KEY} HAIBUN_O_OUTREVIEWS_URI_ARGS=${_O_OUTREVIEWS_URI_ARGS} npm run test-pipeline-indexes


  # - job: publish_e2e_artifacts
  #   dependsOn: e2etests
  #   steps:
  #     - publish: '$(System.DefaultWorkingDirectory)'
  #       artifact: e2e_capture
  #       displayName: Publish e2e artifact            

  # - job: exit_if_failed
  #   dependsOn: publish_e2e_artifacts
  #   condition: eq(dependencies.e2etests.result,'Succeeded')
  #   steps:
  #     - script: echo e2e tests passed, continuing.

  - task: PublishTestResults@2
    inputs:
      testResultsFormat: 'JUnit'
      testResultsFiles: 'junit/**.xml'