resources:
  pipelines:
  - pipeline: post-pr-e2e-tests
    project: gccollab-IaC-resources
    source: gctools-outilsgc.gcconnex - PR
    trigger: true

variables:
  HAIBUN_ENVC: username=Haibun,password=Haibun,gccollab login=https://gccollab-dev-pr-$(System.PullRequest.PullRequestId).azurewebsites.net/login-ouverturedesession/,post login=https://gccollab-dev-pr-$(System.PullRequest.PullRequestId).azurewebsites.net/profile/Haibun,gccollab newsfeed=https://gccollab-dev-pr-$(System.PullRequest.PullRequestId).azurewebsites.net/newsfeed/
  HAIBUN_SETTING: pullrequest-

jobs:
  - job: e2etests
    pool:
        vmImage: 'ubuntu-latest'

    container:
        image: mcr.microsoft.com/playwright:focal
        volumes: [e2e-reviews]

    steps:
        # - checkout: e2etest     
        - task: Npm@1
          inputs:
            command: 'install'
          displayName: 'installing dependencies'
# using CmdLine for the following instead of Npm because npm buffers the entire output
        - task: CmdLine@2
          inputs:
            HAIBUN_ENVC: $(HAIBUN_ENVC)
          displayName: 'make junit test directory'
          continueOnError: false
          inputs:
            script: |
              mkdir junit
        - task: CmdLine@2 
          inputs:
            HAIBUN_ENVC: $(HAIBUN_ENVC)
          displayName: 'Running path e2e tests'
          continueOnError: true

          inputs:
            script: |
              npm run test-pr-happy

        # - task: CmdLine@2
          inputs:
            HAIBUN_ENVC: $(HAIBUN_ENVC)
        #   displayName: 'Running a11y e2e tests'
        #   continueOnError: true
        #   inputs:
        #     script: |
        #       npm run test-pr-a11y

        - task: CmdLine@2
          inputs:
            HAIBUN_ENVC: $(HAIBUN_ENVC)
          displayName: 'Running regression e2e tests'
          continueOnError: true
          inputs:
            script: |
              npm run test-pr-regressions
 
#        - task: CmdLine@2 
        #   displayName: 'Generate sarif indexes'
        #   continueOnError: true
        #   inputs:
        #     script: |
        #       HAIBUN_DEST=sarif HAIBUN_O_AZURESTORAGEBLOB_DESTINATION='staticanalysis-sc' HAIBUN_O_SARIF_TRACE_STORAGE=AzureStorageBlob HAIBUN_O_SARIF_INDEX_STORAGE=StorageFS HAIBUN_O_AZURESTORAGEBLOB_ACCOUNT=${_O_AZURESTORAGEBLOB_ACCOUNT} HAIBUN_O_AZURESTORAGEBLOB_KEY=${_O_AZURESTORAGEBLOB_KEY}  npm run test-pipeline-index-sarif

        - task: CmdLine@2
          displayName: 'Generate test result indexes'
          continueOnError: true
          inputs:
            script: |
              npm run publish-azure-captures-indexes

        - task: PublishTestResults@2
          inputs:
            testResultsFormat: 'JUnit'
            testResultsFiles: 'junit/**.xml'

  # - job: publish_e2e_artifacts
  #   dependsOn: e2etests
  #   steps:
  #     - publish: '$(System.DefaultWorkingDirectory)'
  #       artifact: e2e_capture
  #       displayName: Publish e2e artifact            

  # - job: exit_if_failed
  #   dependsOn: publish_e2e_artifacts
  #   condition: eq(dependencies.e2etests.result,'Succeeded')
  #   steps:
  #     - script: echo e2e tests passed, continuing.

  # - job: publish_junit_results
  #   dependsOn: e2etests
  #   steps:
