resources:
  pipelines:
  - pipeline: post-pr-e2e-tests
    project: gccollab-IaC-resources
    source: gctools-outilsgc.gcconnex - PR
    trigger: true

jobs:
  - job: e2etests
    pool:
        vmImage: 'ubuntu-latest'

    # container:
        # image: mcr.microsoft.com/playwright:v1.40.1-jammy
        # volumes: [e2e-reviews]

    steps:
        # - checkout: e2etest     
        - task: Npm@1
          inputs:
            command: 'install'
          displayName: 'installing dependencies'

        - task: CmdLine@2
          displayName: 'playwright deps'
          inputs:
            script: |
              npx playwright install

        # - task: CmdLine@2
        #   displayName: 'install playwright deps'
        #   inputs:
        #     script: |
        #       npx playwright install --with-deps

        - task: CmdLine@2
          displayName: 'make junit test directory'
          continueOnError: false
          inputs:
            script: |
              mkdir junit

# using CmdLine for the following instead of Npm because npm buffers the entire output
        - task: CmdLine@2 
          displayName: 'Running path e2e tests'
          continueOnError: true
          inputs:
            script: |
              npm run test-pr-happy

        - task: CmdLine@2
          displayName: 'Running a11y e2e tests'
          continueOnError: true
          inputs:
            script: |
              npm run test-pr-a11y

        - task: CmdLine@2
          displayName: 'Running regression e2e tests'
          continueOnError: true
          inputs:
            script: |
              npm run test-pr-regressions
 
        - task: CmdLine@2
          displayName: 'Publish test result history'
          continueOnError: true
          inputs:
            script: |
              npm run publish-history-azure

        - task: CmdLine@2
          displayName: 'Publish dashboard'
          continueOnError: true
          inputs:
            script: |
              pwd
              ls -la
              npm run publish-reviewer-azure

        - task: PublishTestResults@2
          inputs:
            testResultsFormat: 'JUnit'
            testResultsFiles: 'junit/**.xml'

  # - job: publish_e2e_artifacts
  #   dependsOn: e2etests
  #   steps:
  #     - publish: '$(System.DefaultWorkingDirectory)'
  #       artifact: e2e_capture
  #       displayName: Publish e2e artifact            

  # - job: exit_if_failed
  #   dependsOn: publish_e2e_artifacts
  #   condition: eq(dependencies.e2etests.result,'Succeeded')
  #   steps:
  #     - script: echo e2e tests passed, continuing.

  # - job: publish_junit_results
  #   dependsOn: e2etests
  #   steps:

